In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os

In [2]:
tf.__version__

'2.8.0'

In [3]:
os.getcwd()

'C:\\Users\\giannis\\Desktop\\Machine+Learning+A-Z+(Codes+and+Datasets)\\Machine Learning A-Z (Codes and Datasets)\\Part 8 - Deep Learning\\Section 39 - Artificial Neural Networks (ANN)\\Python'

In [4]:
os.chdir('C:\\Users\\giannis\\Downloads\\financial_data.csv')

In [5]:
os.getcwd()

'C:\\Users\\giannis\\Downloads\\financial_data.csv'

In [6]:
dataset = pd.read_csv('financial_data.csv')
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

In [7]:
dataset

entry_id  age  pay_schedule  home_owner  income  months_employed  \
0       7629673   40     bi-weekly           1    3135                0   
1       3560428   61        weekly           0    3180                0   
2       6934997   23        weekly           0    1540                6   
3       5682812   40     bi-weekly           0    5230                0   
4       5335819   33  semi-monthly           0    3590                0   
...         ...  ...           ...         ...     ...              ...   
17903   9949728   31       monthly           0    3245                0   
17904   9442442   46     bi-weekly           0    6525                0   
17905   9857590   46        weekly           0    2685                0   
17906   8708471   42     bi-weekly           0    2515                0   
17907   1498559   29        weekly           1    2665                0   

       years_employed  current_address_year  personal_account_m  \
0                   3                     3                   6   
1                   6                     3                   2   
2                   0                     0                   7   
3                   6                     1                   2   
4                   5                     2                   2   
...               ...                   ...                 ...   
17903               5                     3                   2   
17904               2                     1                   3   
17905               5                     1                   1   
17906               3                     5                   6   
17907               4                    10                   4   

       personal_account_y  ...  amount_requested  risk_score  risk_score_2  \
0                       2  ...               550       36200      0.737398   
1                       7  ...               600       30150      0.738510   
2                       1  ...               450       34550      0.642993   
3                       7  ...               700       42150      0.665224   
4                       8  ...              1100       53850      0.617361   
...                   ...  ...               ...         ...           ...   
17903                   6  ...               700       71700      0.691126   
17904                   3  ...               800       51800      0.648525   
17905                   8  ...              1200       59650      0.677975   
17906                   1  ...               400       80200      0.642741   
17907                   1  ...               600       64950      0.720889   

       risk_score_3  risk_score_4  risk_score_5  ext_quality_score  \
0          0.903517      0.487712      0.515977           0.580918   
1          0.881027      0.713423      0.826402           0.730720   
2          0.766554      0.595018      0.762284           0.531712   
3          0.960832      0.767828      0.778831           0.792552   
4          0.857560      0.613487      0.665523           0.744634   
...             ...           ...           ...                ...   
17903      0.928196      0.664112      0.838012           0.727705   
17904      0.970832      0.699241      0.844724           0.774918   
17905      0.918141      0.687981      0.939101           0.472045   
17906      0.885684      0.456448      0.686823           0.406568   
17907      0.874372      0.505565      0.631619           0.846163   

       ext_quality_score_2  inquiries_last_month  e_signed  
0                 0.380918                    10         1  
1                 0.630720                     9         0  
2                 0.531712                     7         0  
3                 0.592552                     8         1  
4                 0.744634                    12         0  
...                    ...                   ...       ...  
17903             0.627705                     2         0  
17904             0.474918         

In [8]:
print(X)

[[40 'bi-weekly' 1 ... 0.580918 0.380918 10]
 [61 'weekly' 0 ... 0.73072 0.63072 9]
 [23 'weekly' 0 ... 0.531712 0.531712 7]
 ...
 [46 'weekly' 0 ... 0.472045 0.672045 9]
 [42 'bi-weekly' 0 ... 0.406568 0.406568 3]
 [29 'weekly' 1 ... 0.8461629999999999 0.8461629999999999 4]]


In [9]:
print(y)

[1 0 0 ... 0 1 1]


In [10]:
##One hot encoding the "pay_schedule"

In [11]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[1.0 0.0 0.0 ... 0.580918 0.380918 10]
 [0.0 0.0 0.0 ... 0.73072 0.63072 9]
 [0.0 0.0 0.0 ... 0.531712 0.531712 7]
 ...
 [0.0 0.0 0.0 ... 0.472045 0.672045 9]
 [1.0 0.0 0.0 ... 0.406568 0.406568 3]
 [0.0 0.0 0.0 ... 0.8461629999999999 0.8461629999999999 4]]


In [13]:
##Splitting the dataset into the Training set and Test set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [15]:
### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
print(X)

[[1.0 0.0 0.0 ... 0.580918 0.380918 10]
 [0.0 0.0 0.0 ... 0.73072 0.63072 9]
 [0.0 0.0 0.0 ... 0.531712 0.531712 7]
 ...
 [0.0 0.0 0.0 ... 0.472045 0.672045 9]
 [1.0 0.0 0.0 ... 0.406568 0.406568 3]
 [0.0 0.0 0.0 ... 0.8461629999999999 0.8461629999999999 4]]


In [18]:
## Part 2 - Building the ANN

In [19]:
### Initializing the ANN


In [20]:
ann = tf.keras.models.Sequential()

In [21]:
### Adding the input layer and the first hidden layer

In [98]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

In [99]:
### Adding the second hidden layer

In [100]:
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

In [101]:
### Adding the output layer

In [102]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [103]:
## Part 3 - Training the ANN


In [104]:
### Compiling the ANN

In [105]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [106]:
### Training the ANN on the Training set

In [107]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 296)

Epoch 1/296
448/448 [==============================] - 2s 2ms/step - loss: 0.5304 - accuracy: 0.7542
Epoch 2/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5043 - accuracy: 0.7702
Epoch 3/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5060 - accuracy: 0.7704
Epoch 4/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5031 - accuracy: 0.7739
Epoch 5/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5028 - accuracy: 0.7709
Epoch 6/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5042 - accuracy: 0.7707
Epoch 7/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5026 - accuracy: 0.7738
Epoch 8/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5000 - accuracy: 0.7751
Epoch 9/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5027 - accuracy: 0.7722
Epoch 10/296
448/448 [==============================] - 1s 2ms/step - loss: 0.5012 - accura

In [108]:
dataset.head()

entry_id  age  pay_schedule  home_owner  income  months_employed  \
0   7629673   40     bi-weekly           1    3135                0   
1   3560428   61        weekly           0    3180                0   
2   6934997   23        weekly           0    1540                6   
3   5682812   40     bi-weekly           0    5230                0   
4   5335819   33  semi-monthly           0    3590                0   

   years_employed  current_address_year  personal_account_m  \
0               3                     3                   6   
1               6                     3                   2   
2               0                     0                   7   
3               6                     1                   2   
4               5                     2                   2   

   personal_account_y  ...  amount_requested  risk_score  risk_score_2  \
0                   2  ...               550       36200      0.737398   
1                   7  ...               600       30150      0.738510   
2                   1  ...               450       34550      0.642993   
3                   7  ...               700       42150      0.665224   
4                   8  ...              1100       53850      0.617361   

   risk_score_3  risk_score_4  risk_score_5  ext_quality_score  \
0      0.903517      0.487712      0.515977           0.580918   
1      0.881027      0.713423      0.826402           0.730720   
2      0.766554      0.595018      0.762284           0.531712   
3      0.960832      0.767828      0.778831           0.792552   
4      0.857560      0.613487      0.665523           0.744634   

   ext_quality_score_2  inquiries_last_month  e_signed  
0             0.380918                    10         1  
1             0.630720                     9         0  
2             0.531712                     7         0  
3             0.592552                     8         1  
4             0.744634                    12         0  

[5 rows x 21 columns]

In [109]:
## Part 4 - Making the predictions and evaluating the model
### Predicting the result of a single observation

In [110]:
print(X)

[[1.0 0.0 0.0 ... 0.580918 0.380918 10]
 [0.0 0.0 0.0 ... 0.73072 0.63072 9]
 [0.0 0.0 0.0 ... 0.531712 0.531712 7]
 ...
 [0.0 0.0 0.0 ... 0.472045 0.672045 9]
 [1.0 0.0 0.0 ... 0.406568 0.406568 3]
 [0.0 0.0 0.0 ... 0.8461629999999999 0.8461629999999999 4]]


In [111]:
print(ann.predict(sc.transform([[60,1.0,0.0,1.0,1,2500,3,1,600,37000,0.7373, 0.9035, 0.4877, 0.515977, 0.580918, 0.380918, 10, 0, 0, 0, 36, 30]]))>0.5)

[[ True]]


In [112]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 1]
 [1 1]
 [0 0]
 ...
 [1 1]
 [0 1]
 [1 1]]


In [113]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 804  850]
 [ 726 1202]]


0.5600223338916807

In [114]:
import matplotlib.pyplot as plt

In [115]:
print(X_train)

[[-1.22463801 -0.30236006 -0.35607494 ... -1.06005855 -1.05738616
   1.7844941 ]
 [-1.22463801  3.30731512 -0.35607494 ...  0.04180056 -0.67208556
  -0.66336864]
 [ 0.81656783 -0.30236006 -0.35607494 ...  0.5883578  -0.84155028
   1.2405246 ]
 ...
 [ 0.81656783 -0.30236006 -0.35607494 ... -1.44456442 -1.44152051
   0.42457036]
 [-1.22463801 -0.30236006  2.80839755 ...  0.13117339  0.84818866
  -0.66336864]
 [ 0.81656783 -0.30236006 -0.35607494 ...  1.40594842 -0.7402435
  -0.93535339]]


In [116]:
print(X_test)

[[-1.22463801 -0.30236006  2.80839755 ...  0.31451697 -0.39963265
   0.6965551 ]
 [ 0.81656783 -0.30236006 -0.35607494 ... -0.78161265 -0.06371543
  -1.20733813]
 [-1.22463801 -0.30236006  2.80839755 ... -0.50556597 -0.50342934
  -0.39138389]
 ...
 [ 0.81656783 -0.30236006 -0.35607494 ...  0.09169007 -0.62224425
  -0.93535339]
 [ 0.81656783 -0.30236006 -0.35607494 ... -1.49100907 -0.77242642
  -0.66336864]
 [-1.22463801 -0.30236006 -0.35607494 ... -1.39050671  0.75896658
  -0.11939914]]


In [117]:
print(y_train)

[0 1 0 ... 1 1 1]


In [118]:
print(y_test)

[1 1 0 ... 1 1 1]


In [148]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [149]:
print(classifier.predict(sc.transform([[60,1.0,0.0,1.0,1,2500,3,1,600,37000,0.7373, 0.9035, 0.4877, 0.515977, 0.580918, 0.380918, 10, 0, 0, 0, 36, 30]])))

[0]


In [150]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [0 0]
 ...
 [0 1]
 [1 1]
 [1 1]]


In [151]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1006  648]
 [ 883 1045]]


0.5725851479620324

In [143]:
##Logistic regression

In [144]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [145]:
print(classifier.predict(sc.transform([[60,1.0,0.0,1.0,1,2500,3,1,600,37000,0.7373, 0.9035, 0.4877, 0.515977, 0.580918, 0.380918, 10, 0, 0, 0, 36, 30]])))

[0]


In [146]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 0]
 ...
 [0 1]
 [1 1]
 [1 1]]


In [147]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 682  972]
 [ 571 1357]]


0.5692350642099386

In [164]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(p=3)

In [165]:
print(classifier.predict(sc.transform([[60,1.0,0.0,1.0,1,2500,3,1,600,37000,0.7373, 0.9035, 0.4877, 0.515977, 0.580918, 0.380918, 10, 0, 0, 0, 36, 30]])))

[0]


In [166]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1006  648]
 [ 883 1045]]


0.5725851479620324